### ISSUE TITLE
general documentation

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/beat_routine#1]
Following the [octave_template](https://github.com/eurobench/pi_octave_csic), we would expect to find at the root:

* README file, with general information, plus command to use the code
* License file

**Comment by aremazeilles** [comment]
@juritaborri, the code is under GPLG v3, is that correct?

**Comment by juritaborri** [comment]
Yes, it it correct.
As regards the README file, should I prepare it?

**Comment by aremazeilles** [comment]
That would be great.

You can have a look at the one from the octave example: https://github.com/eurobench/pi_octave_csic

For now you could skip the docker part. But it would be great that you indicate what is your code about and how to launch your code.

**Comment by juritaborri** [comment]
Ok, thanks for the skeleton.
I suppose I have to fill one per each routine, is it right?
