### ISSUE TITLE
Header in Platform data

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/beat_routine#10]
Platform data files should have a header, with the label of each column.

Also (maybe to be treated later on), it is good practice to define the column of interest based on the header labels. If not, any change in the column order (for any reason) makes your code not working anymore. If you verify the column of interest is in the the file, and get its idea, the column order can change, you are not affected.

AS an example, what we do in our sample:

* [here](https://github.com/eurobench/pi_octave_csic/blob/master/src/computePI.m#L32) to load the header
* [here](https://github.com/eurobench/pi_octave_csic/blob/master/src/calculate_spatiotemporal.m#L36) to search the label of interest id in the file

**Comment by juritaborri** [comment]
I created new branch with modified files according this suggestion

**Comment by aremazeilles** [comment]
If you are done, can you go to the root of the repo, branches -> and create a pull request (indicating it would fix that issue), and assign it to me?
