### ISSUE TITLE
File format: emg labels

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/beat_routine#28]
from #26:

> entries are prefixed with `r_` and `l_`. 
>@alfonsotecnalia should we then propose this updgrade to the [documentation](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#electromyography-file)?

**Comment by alfonsotecnalia** [comment]
We were considering suffixes when talking about [joints/links in the human model](https://github.com/aremazeilles/eurobench_documentation/issues/63). Shouldn't we use suffixes also here in order to keep coherence?

**Comment by aremazeilles** [comment]
Would it be acceptable @juritaborri to use suffixes?

**Comment by juritaborri** [comment]
Yes, it is ok!
I have added a new branches with the modifications in emg.csv (input data) and in EMG_routine script

**Comment by aremazeilles** [comment]
Good, Once you have uploaded your branch, you could have go to the branch page on github, and click on the merge request button, then assign it to me. This way, the CI process is launched, and I can see easily from the website the changes proposed.
I did it, no worry :)

**Comment by aremazeilles** [comment]
Fixed by #32
