### ISSUE TITLE
Error when executing docker and the output folder does not exist

### ISSUE THREAD

**Issue by alfonsotecnalia** [aremazeilles/beat_routine#41]
I have tested with run_protocol_1 (docker run ...) but the PiManager also fails when calling it automatically. The output folder is created but nothing is written (I suppose because of permissions). The following lines appear in console:
```
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
csv file: /in/jointAngles.csv
platform data: /in/platformData.csv
emg data : /in/emg.csv
result folder : /out
warning: function /usr/share/octave/packages/linear-algebra-2.2.2/condeig.m shadows a core library function
warning: called from
    load_packages_and_dependencies at line 48 column 5
    load_packages at line 47 column 3
    pkg at line 411 column 7
    ./run_protocol1 at line 26 column 2
Running kinematic_routine_walking
fs_platform =  200
Same sample frequency
error: fprintf: invalid stream number = -1
error: called from
    kinematic_routine_walking at line 98 column 1
    ./run_protocol1 at line 29 column 1
```

If the output folder is created previously there is no error.

**Comment by aremazeilles** [comment]
I understand that you state an error when the folder for output is not existing. 

The application is not supposed to create the folder, as it can generates some right issues. I ask to all to place output files in a folder, assuming the folder exists. 

An improvement could be checking whether the folder already exists. 
Is it what you are looking for?

**Comment by alfonsotecnalia** [comment]
I think the error is in another part. I have tried bestable and happens the same when running the command but bestable works when running the PiManager. I will close this issue.

**Comment by alfonsotecnalia** [comment]
The error was in the entry point in yaml: run_protocolX (right) vs run_protocol_X (in yal, worng)
