### ISSUE TITLE
Elements inside matrix results separated by spaces

### ISSUE THREAD

**Issue by alfonsotecnalia** [aremazeilles/beat_routine#44]
The elements in the rows of matrix result files are separated by spaces (for example rom_p). It should be separated commas (`,`). Would you mind changing it?

**Comment by aremazeilles** [comment]
It seems file of format `pi_phi` and `pi_romp`should be adjusted

**Comment by aremazeilles** [comment]
Maybe @juritaborri dd not answer becasue he did not that issue. I will have a quick look at it to see if I can solve it, and let you know
