### ISSUE TITLE
kinematic_routine_walking

### ISSUE THREAD

**Issue by aremazeilles** [aremazeilles/beat_routine#7]
When launching the code from octave interface, I get the following message:

```octave
kinematic_routine_walking("input/subject_01_run_01_jointAngles.csv", "input/subject_01_run_01_PlatformData_protocol1.csv")
fs_platform =  200
Same sample frequencyerror: invalid use of script /home/anthony/code/eurobench/beat_routine/beat/AdditionalFunctions/appendmirror.min index expression
error: called from
    upresample at line 4 column 3
    eventsnormalize at line 16 column 37
    kinematic_routine_walking at line 56 column 30
```

**Comment by aremazeilles** [comment]
right before, I just made, from the root of your folder:

```
>> addpath("beat/Functions")
>> addpath("beat/AdditionalFunctions")
>> pkg load io
```

**Comment by aremazeilles** [comment]
OK, I got  it, text "help" was present in file appendmirror.m ...

**Comment by juritaborri** [comment]
Yes, it is a misprint!

**Comment by aremazeilles** [comment]
I will adjust it, and tell you. 
Could make it work. 
But is there any reason for having the main script in beat/Scrit folder?
Could it be moved elsewhere?

**Comment by juritaborri** [comment]
There is not a real reason. I have arranged documents how I thought better, but I am open to any changes

**Comment by aremazeilles** [comment]
Handled in #8
